name: Test React App
trigger: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repositiry code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
